### ISSUE TITLE
Can't handle Json deserialization exceptions

### ISSUE THREAD

**Issue by cluka** [Kahbazi/MediatR.AspNetCore.Endpoints#13]
As I see in the code, the deserialization exceptions (JsonException..) is swallowed. There is no Log entry written and the exception is not re-thrown. So When the exception happens, we only get Status Code 400 but not error why.

**Comment by Kahbazi** [comment]
Hi @cluka 
There's now an `OnDeserializeError` options, which lets you control what happens when an exception occurs during deserialization. 

https://github.com/Kahbazi/MediatR.AspNetCore.Endpoints/blob/4f5d5fec2d636d4d4b1696d7de7dc68657562828/src/MediatR.AspNetCore.Endpoints/EndpointRouteBuilderExtensions.cs#L55-L66

https://github.com/Kahbazi/MediatR.AspNetCore.Endpoints/blob/4f5d5fec2d636d4d4b1696d7de7dc68657562828/src/MediatR.AspNetCore.Endpoints/MediatorEndpointOptions.cs#L12-L16

Let me know if this works for you and I will create a release.

**Comment by cluka** [comment]
Ok, this i very clean and it works for me.
